// <auto-generated />
using System;
using LibraryManagementApp.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementApp.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1828, 9, 9),
                            Name = "Lev Tolstoy"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1821, 11, 11),
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1799, 6, 6),
                            Name = "Alexander Pushkin"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(1891, 5, 15),
                            Name = "Mikhail Bulgakov"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateOnly(1860, 1, 29),
                            Name = "Anton Chekhov"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateOnly(1775, 12, 16),
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateOnly(1812, 2, 7),
                            Name = "Charles Dickens"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateOnly(1883, 7, 3),
                            Name = "Franz Kafka"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateOnly(1903, 6, 25),
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateOnly(1927, 3, 6),
                            Name = "Gabriel Garcia Marquez"
                        });
                });

            modelBuilder.Entity("LibraryManagementApp.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublishedYear = 1869,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            PublishedYear = 1877,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            PublishedYear = 1866,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            PublishedYear = 1880,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            PublishedYear = 1833,
                            Title = "Eugene Onegin"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            PublishedYear = 1836,
                            Title = "The Captain's Daughter"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            PublishedYear = 1967,
                            Title = "The Master and Margarita"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            PublishedYear = 1925,
                            Title = "Heart of a Dog"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            PublishedYear = 1904,
                            Title = "The Cherry Orchard"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            PublishedYear = 1892,
                            Title = "Ward No. 6"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 6,
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            PublishedYear = 1815,
                            Title = "Emma"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            PublishedYear = 1838,
                            Title = "Oliver Twist"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 7,
                            PublishedYear = 1861,
                            Title = "Great Expectations"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 8,
                            PublishedYear = 1925,
                            Title = "The Trial"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 8,
                            PublishedYear = 1926,
                            Title = "The Castle"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 9,
                            PublishedYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 10,
                            PublishedYear = 1967,
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            PublishedYear = 1975,
                            Title = "The Autumn of the Patriarch"
                        });
                });

            modelBuilder.Entity("LibraryManagementApp.Domain.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagementApp.Domain.Entities.Author", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("LibraryManagementApp.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
